projects/valtimo/account/package.json, projects/valtimo/auth0/package.json, projects/valtimo/authority/package.json, projects/valtimo/choice-field/package.json, projects/valtimo/choicefield/package.json, projects/valtimo/components/package.json, projects/valtimo/context/package.json, projects/valtimo/dashboard/package.json, projects/valtimo/document/package.json, projects/valtimo/dossier/package.json, projects/valtimo/keycloak/package.json, projects/valtimo/layout/package.json, projects/valtimo/management/package.json, projects/valtimo/process/package.json, projects/valtimo/security/package.json, projects/valtimo/task/package.json, projects/valtimo/user-management/package.json, projects/valtimo/view-configurator/package.json
Removed redundant publish configs from each library's package.json file. These configurations are no longer needed, since the libraries are now published publicly to NPM.
=> feat: remove publish configs from package.json files

projects/valtimo/layout/src/beagle/src/js/app.js
In the current version it's not possible to see the menu on a mobile devices (or with a smaller resolution), because it is missing a specific "open" class that should be applied when the menu open is triggered. It's seems that the issue is in the beagle file, but I was not able to find anything in the official documentation. Not sure when this functionality broke but it has been working in older versions.
=> Add extra toggle class to display the menu component which is currently hidden on mobile and smaller screens

projects/valtimo/components/src/lib/form-io/form-io.component.html, projects/valtimo/components/src/lib/form-io/form-io.component.ts, projects/valtimo/connector-management/src/lib/components/edit-product-aanvragen-connector/edit-product-aanvragen-connector.component.html
Property was used as a quick fix for upload components, but is causing other issues with locale based number formatting among others. Since upload component has been refactored this property is not needed anymore.
=> Removed property used to block refresh of formio form

projects/valtimo/config/src/lib/translation/assets/core/de.json, projects/valtimo/config/src/lib/translation/assets/core/en.json, projects/valtimo/config/src/lib/translation/assets/core/nl.json, projects/valtimo/contact-moment/src/lib/contact-moment.service.ts, projects/valtimo/contact-moment/src/public_api.ts, projects/valtimo/contract/src/lib/contact-moment.model.ts, projects/valtimo/contract/src/public-api.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/contact-moments/contact-moments.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/contact-moments/contact-moments.component.scss, projects/valtimo/dossier/src/lib/dossier-detail/tab/contact-moments/contact-moments.component.ts
Adds a button on the contact moments tab on a dossier detail page, which opens a popup which allows the user to manually save a note of a contact moment. Closes https://ritense.tpondemand.com/entity/32838-aantekening-van-klantcontact-vastleggen-buiten-proces
=> feat: popup to save note on contact moments tab

projects/valtimo/config/src/lib/config.service.ts
Closes https://ritense.tpondemand.com/entity/32891-api-url-zonder-op-het-eind
=> fix: make environmnet agnostic about trailing slash, format in config service

projects/valtimo/config/src/lib/config.service.ts
* fixed custom translations not being found (404 errors) when prefixes for custom translations are missing a trailing '/'
=> feat: slash agnostic translationResources prefix

projects/valtimo/task/src/lib/task-detail-modal/task-detail-modal.component.ts
* modified task modal subtitle to show task creation timestamp correctly instead of "Invalid Date"
=> fix: task modal subtitle timestamp

projects/valtimo/config/src/lib/services/menu-include.service.ts
The klanten menu checked against the old HaalCentraal connector. It will now check against the new HaalCentraalBrp connector
=> bugfix 33714 - Klanten menu fix

package-lock.json, package.json, projects/valtimo/components/package.json, projects/valtimo/management/package.json, projects/valtimo/user-management/package.json
@ng-bootstrap/ng-bootstrap version 12 was not compatible with bootstrap version 4 used by Valtimo: https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap. Closes https://ritense.tpondemand.com/entity/36385-fe-bootstrap-version-is-incompatible-with
=> fix: downgrade @ng-bootstrap/ng-bootstrap

projects/valtimo/user-interface/src/lib/components/title/title.component.html
Having ng-content twice, only the second one was rendering, meaning that H1 elements did not show any contents. Thanks to this tip, this has been resolved: https://github.com/angular/angular/issues/22972#issuecomment-407358396
=> fix: fix title component

projects/valtimo/config/src/lib/models/config.ts
change the type of default direction to string
US: https://ritense.tpondemand.com/entity/36161-fe-configurable-sorting-direction-case-list
=> fix: change the type of default direction to string

projects/valtimo/user-interface/assets/design-tokens.css, projects/valtimo/user-interface/src/lib/components/select/select.component.scss
* change the select background color variable to white
* added shadow in selector for contrast
* removed hover from select when component disabled
* changed select background color when disabled
* added new color variables for the select component
US: https://ritense.tpondemand.com/entity/36692-fe-new-design-dropdown-seems-disabled
=> feat: new design dropdown seems disabled

projects/valtimo/components/src/lib/components/list/list.component.ts, projects/valtimo/components/src/lib/models/index.ts, projects/valtimo/components/src/lib/models/list.model.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.html, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts, projects/valtimo/user-interface/src/lib/components/title/title.component.html
Refactor case list component to work with observables, fix issues:
- Go to correct page number on switching case definitions
- Fix pagination indicator showing new page number on switching case definitions  
- Call function to get initial sort state infinitely from component code
- Switch to last available page on choosing a larger page size
- Go to first page on typing in search term or sequence for searching
- On case definition load: get pagination (including sorting) from cache. If this does not exist, get default pagination and sorting (from environment)
- On switching case definitions, the sort state of the previously selected case definition was used. This has now been fixed, and the case definition uses either its cached sort state or default sort state (environment)
- Does not …
=> feat: fix case list pagination with observables

projects/valtimo/components/src/lib/components/form-io/form-io-builder.component.ts
https://ritense.tpondemand.com/entity/36311-be-resolve-zaakobject-variables-for-task
=> 36311: Removed FormIO key field validation to allow for expressions in keys

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/dossier/src/lib/dossier-detail/tab/progress/progress.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/progress/progress.component.ts
We have a situation where we already have a case/dossier in Valtimo, but no active process yet since we start the process with sub process task. Right now Valtimo assumes that there is atleast one process active in the progress tab (or has been active) but for us that is not the case.
=> Add empty state if no documentInstance have been started yet

projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.html, projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.ts, projects/valtimo/components/src/lib/models/documenten-api-metadata.model.ts, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/document/src/lib/document.service.ts, projects/valtimo/document/src/lib/models/document.model.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.ts, projects/valtimo/resource/src/lib/models/upload.model.ts, projects/valtimo/resource/src/lib/services/open-zaak-upload.service.ts, projects/valtimo/resource/src/lib/services/open-zaak.service.ts, projects/valtimo/resource/src/lib/services/upload-provider.service.ts
Also uses new upload endpoint. Closes https://ritense.tpondemand.com/entity/37438-fe-get-document-types-from-catalogi
=> feat: get document types, use new upload endpoint

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/s3-documents/s3-documents.component.ts, projects/valtimo/keycloak/src/lib/keycloak-user.service.ts, projects/valtimo/user-interface/src/lib/components/button/button.component.ts, projects/valtimo/user-interface/src/lib/components/prompt/prompt.component.html, projects/valtimo/user-interface/src/lib/components/prompt/prompt.component.ts, projects/valtimo/user-interface/src/lib/services/prompt.service.ts, src/environments/environment.ts
Add prompt when deleting a file, fixed a bug with the keycloak prompt always overriding the body text and added the option to show different types of buttons in the prompt.
The story for this feature: https://ritense.tpondemand.com/restui/board.aspx?#page=userstory/3711037110
=> Add prompt when deleting files

projects/valtimo/components/src/lib/components/form-io/documenten-api-uploader/documenten-api-uploader.component.html, projects/valtimo/components/src/lib/components/form-io/documenten-api-uploader/documenten-api-uploader.component.ts, projects/valtimo/components/src/lib/components/form-io/documenten-api-uploader/documenten-api-uploader.formio.ts
Also changes category of formio component from basic to advanced. Closes https://ritense.tpondemand.com/entity/37552-fe-add-check-in-new-documenten and https://ritense.tpondemand.com/entity/37554-fe-move-documenten-api-formio-upload
=> feat: check if upload process link is checked inside new formio component

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/document/src/lib/models/document.model.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts, src/environments/environment.ts
- A default column has been added to the case list page
- This column has the header 'assignee'
- The list can be sorted on the 'assignee' column, sort on firstname then lastname
US: https://ritense.tpondemand.com/entity/37406-fe-show-case-assignee-in-case
=> feat: show case assignee

package-lock.json, projects/valtimo/dossier/src/lib/models/tabs.model.ts
Functional: If I navigate directly to http://localhost:4200/dossiers/leningen/document/0d9dd2b8-0ee8-4bef-8799-108515b3ca7c/summary?test=test, the query params are retained. If I navigate to other tabs, the params are lost. If I navigate then back to summary tab, the params are also not there anymore.
=> feat: fix query params on keycloak redirect case tabs

projects/valtimo/form-link/src/lib/services/process-link.service.ts
The BE expects a null when saving an empty plugin link property
=> fix: 42785 Saving optional plugin link properties

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/dossier-management/src/lib/dossier-management-upload/dossier-management-upload.component.html, projects/valtimo/dossier-management/src/lib/dossier-management-upload/dossier-management-upload.component.ts, projects/valtimo/form-management/src/lib/form-management-upload/form-management-upload.component.html, projects/valtimo/form-management/src/lib/form-management-upload/form-management-upload.component.ts
- Bugfix: "Upload" button was incorrectly enabled when uploading a correct file, but then replacing it with an incorrect file
- Added a user-friendly error message if the submitted .json file contains an incorrect JSON string
- Applied both changes to the case definition upload form and the form definition upload form
=> Improvement to case and form definition upload

projects/valtimo/task/src/lib/task-detail-modal/task-detail-modal.component.ts, projects/valtimo/user-interface/src/lib/services/prompt.service.ts
Fixes bug: 
When navigating away from the form in a form flow, and the prompt shows up, and then clicking the 'x' to close the prompt. It is no longer possible to submit the form
=> Bugfix: fix form-flow back button prompt close button

projects/valtimo/dossier/src/lib/dossier-detail/dossier-detail.component.html
We are not using the assignee case option, but want the custom dossier header. Currently the custom dossier header stream is never hit if the canHaveAssignee options is disabled.
=> Fix custom header not working if canHaveAssignee is not enabled

projects/valtimo/form-management/src/lib/form-management-create/form-management-create.component.html
TP 51776: clicking 'back' button on new-form-definition page redirected user to the dashboard.
Release note PR: https://github.com/valtimo-platform/valtimo-documentation/pull/270
=> Changed url of back button.

projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/s3-documents/s3-documents.component.ts, projects/valtimo/dossier/src/lib/services/file-sort.service.ts, projects/valtimo/dossier/src/lib/services/index.ts, src/environments/environment.ts
Behind feature toggle because it was easy and it's a feature one specific implementation wanted, can't be sure others want this. Will put in documentation for them for easy reference. Closes https://ritense.tpondemand.com/entity/51591-fe-sort-related-files-by-date
=> feat: sort related file by date

projects/valtimo/object-management/src/lib/components/object-management-modal/object-management-modal.component.ts
When editing a object in the object-management it's currently saving the uuid instead of the name which breaks the forms in the object menu.
=> Form definition uuid value is replaced by the actual string value

projects/valtimo/components/src/lib/components/expansion-panel/expansion-panel.component.html, projects/valtimo/components/src/lib/components/expansion-panel/expansion-panel.component.ts, projects/valtimo/components/src/lib/components/expansion-panel/expansion-panel.module.ts, projects/valtimo/components/src/public_api.ts
The Expansion panel is a Carbon Expandable Tile but with a small tweak.
The boolean property 'hideAboveFoldWhenExpanded' lets you control what happens when the tile is expanded.
The default value false results in the normal operation of the expandable tile. 
When the value is true the collapsed panel is hidden and only the expanded panel is shown
=> feature Expansion Panel

projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.html, projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.ts
These properties were not required in FE, but BE errors if they're empty. This PR makes them required
=> fix: require description and conf. level

projects/valtimo/process-management/src/lib/process-management-builder/process-management-builder.component.html
Instead of looking at the first element of the list of process versions, we look at the latest version now.
=> fix: process definition name not showing

projects/valtimo/object/src/lib/components/object-list/object-list.component.ts
The redirect function was only supporting the default columns (which includes a url) and now it also adds the id when using custom columns.
=> Update redirect function to support custom columns as well

projects/valtimo/components/src/lib/components/form-io/form-io-builder.component.html, projects/valtimo/components/src/lib/components/form-io/form-io-builder.component.ts, projects/valtimo/components/src/lib/components/form-io/form-io.component.html, projects/valtimo/components/src/lib/components/form-io/form-io.component.ts, projects/valtimo/components/src/lib/components/form-io/services/form-io-state.service.ts, projects/valtimo/components/src/lib/models/form-io.model.ts, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json
For one of the our projects we really need to be able to translate Formio forms which is currently not available. Formio already has a feature to translate things. Currently I have added only add some default translations which could increase in the feature. One of the downsides of the Formio translation is that they use a label as translation so implementation should probably always have some translations as well.
=> Enabled the option to tranlate formio forms with minimal translations

projects/valtimo/object/src/lib/components/object-list/object-list.component.ts
=> fix: object-list column type date formatting doesn't work
