README.md, projects/valtimo/contract/src/lib/open-zaak.model.ts, projects/valtimo/open-zaak/src/lib/extension/open-zaak-service-task-connector-modal-extension/open-zaak-service-task-connector-modal-extension.component.html, projects/valtimo/open-zaak/src/lib/extension/open-zaak-service-task-connector-modal-extension/open-zaak-service-task-connector-modal-extension.component.ts, projects/valtimo/resource/src/lib/services/open-zaak.service.ts
=> feat: connect openzaak actions to process definition key

projects/valtimo/components/src/lib/form-io/form-io.component.html, projects/valtimo/components/src/lib/form-io/form-io.component.ts
Closes https://ritense.tpondemand.com/entity/32985-currency-notatie-werkt-niet-op-basis
=> feat: get form.io language from translate service instead of localstorage

projects/valtimo/contract/src/lib/config.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/documents/documents.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/documents/documents.component.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
Added a new configuration option called caseFileSizeUploadLimitMB where you can enter the max file size for the case document uploader.
=> feature 33057 - File size limit is now configurable

gradle.properties
Finally, setting the correct version number. See PR  #33  for the full changelog of this release.
=> Release 4.16.0

.nvmrc, settings.gradle
- changed the project name to be in line with the repo name
- added .nvmrc file for the Node Version Manager, setting the node version to Fermium (14)
=> Fix project name, added NVM support

projects/valtimo/config/src/lib/translation/assets/core/de.json, projects/valtimo/config/src/lib/translation/assets/core/en.json, projects/valtimo/config/src/lib/translation/assets/core/nl.json, projects/valtimo/dossier-management/src/lib/dossier-management-connect-modal/dossier-management-connect-modal.component.html, projects/valtimo/dossier-management/src/lib/dossier-management-detail/dossier-management-detail.component.html
Closes https://ritense.tpondemand.com/entity/28022-fe-add-tooltip-to-init-document
=> feat: improve process case link texts and tooltips

projects/valtimo/components/src/lib/components/dropzone/dropzone.component.ts, src/environments/environment.test.ts
Includes other fix in test env file. Closes https://ritense.tpondemand.com/entity/33604-fe-gzac-uploaden-loopt-spaak-bij
=> fix: reset upload field on error, clear message after timeout

projects/valtimo/process-management/src/lib/process-management-builder/process-management-builder.component.html
Closes comments https://ritense.tpondemand.com/entity/28643-fe-consistency-of-buttons
=> feat: address feedback consistency buttons

package-lock.json, projects/valtimo/layout/ng-package.json, projects/valtimo/layout/package.json
=> fix: remove problematic summernote dep

projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/dossier/src/lib/dossier-detail/dossier-detail.component.html, projects/valtimo/dossier/src/lib/dossier-detail/dossier-detail.component.ts
- Modified config.ts to include customDossierHeader config
- Modified dossier component to load and display the customDossierHeader
=> Added customDossierHeader to the dossier component

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/open-zaak/src/lib/open-zaak-extension/open-zaak-service-task-connector-modal-extension/open-zaak-service-task-connector-modal-extension.component.html
=> #33902 Configureren taak voor maken Zaakbesluit

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json
=> feat: add catalogi url to open-zaak-connector

projects/valtimo/choice-field/src/lib/choice-field-value-list/choice-field-value-list.component.ts
* swapped key and value columns to match column titles
* renamed column titles to accurately reflect the contents inside the respective columns
=> 33904 - Fix choice-fields list columns and column titles

projects/valtimo/customer/src/lib/components/customer-list/customer-list.component.ts
Solves finding 4 on https://ritense.tpondemand.com/entity/33690-personen-zoeken-in-haalcentraal
=> fix: return empty list on get haalcentraal customers error

projects/valtimo/task/src/lib/task-detail-modal/task-detail-modal.component.html, projects/valtimo/task/src/lib/task-detail-modal/task-detail-modal.component.ts
Closes https://ritense.tpondemand.com/entity/35145-fe-ophalen-en-renderen-formulier-definitie
=> feat: check in task modal template on process link type

projects/valtimo/connector-management/src/lib/components/edit-connector-properties/edit-connector-properties.component.ts, projects/valtimo/connector-management/src/lib/components/edit-product-aanvragen-connector/edit-product-aanvragen-connector.component.ts, projects/valtimo/connector-management/src/lib/components/edit-taak-connector/edit-taak-connector.component.ts, projects/valtimo/management/src/lib/management-context/context-edit/context-edit.component.html, projects/valtimo/task/src/lib/task-list/task-list.component.html, projects/valtimo/task/src/lib/task-list/task-list.component.ts, projects/valtimo/user-management/src/lib/user-create/user-create.component.html, projects/valtimo/user-management/src/lib/user-detail/user-detail.component.html
Closes https://ritense.tpondemand.com/entity/35258-fe-verwerken-functionele-feedback-nieuwe-ui
=> fix: functional feedback new ui design

projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/form-link/src/lib/components/form-link-modal/form-link-modal.component.html, projects/valtimo/form-link/src/lib/components/form-link-modal/form-link-modal.component.ts
Closes https://ritense.tpondemand.com/entity/35503-fe-kan-geen-valtimo-project-maken
=> fix: add feature toggle for form flow

projects/valtimo/resource/src/lib/services/download.service.ts
Certain files (based on file extensions) will now open in a new tab. Not supported files are still downloaded as was the case before.
The method used in the function openBlobInNewTab() is chosen because blob can be blocked by adblockers.
Just using window.open won't work because the tab would then open and immediately closed again by the adblocker.
=> feature 35396 - Documents now open in new tab

package-lock.json, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/customer/src/lib/components/cases-list/cases-list.component.html, projects/valtimo/customer/src/lib/components/cases-list/cases-list.component.scss, projects/valtimo/customer/src/lib/components/cases-list/cases-list.component.ts, projects/valtimo/customer/src/lib/components/customer-list/customer-list.component.html, projects/valtimo/customer/src/lib/components/customer-list/customer-list.component.ts, projects/valtimo/customer/src/lib/customer-routing.module.ts, projects/valtimo/customer/src/lib/customer.module.ts, projects/valtimo/customer/src/lib/models/case.ts, projects/valtimo/customer/src/lib/models/index.ts, projects/valtimo/customer/src/lib/services/customer.service.ts, projects/valtimo/user-interface/src/lib/components/table/table.component.html, projects/valtimo/user-interface/src/lib/components/table/table.component.ts, src/environments/environment.ts
=> feat: add hackathon customer cases page

projects/valtimo/task/src/lib/task-list/task-list.component.ts
=> lint fix task list component

projects/valtimo/components/src/lib/components/timeline/timeline.component.html
Closes https://ritense.tpondemand.com/entity/35777-fe-escapen-van-gebruikersinput-bij-contactmomenten
=> feat: sanitize input on timeline component

projects/valtimo/user-interface/src/lib/components/multi-input/multi-input.component.ts
=> fix lint multi input

projects/valtimo/plugin-management/src/lib/models/plugin.model.ts
=> fix: build

package-lock.json, package.json, projects/valtimo/account/package.json, projects/valtimo/components/package.json, projects/valtimo/dashboard/package.json, projects/valtimo/dossier/package.json, projects/valtimo/layout/package.json, projects/valtimo/management/package.json, projects/valtimo/process/package.json, projects/valtimo/task/package.json
for https://ritense.tpondemand.com/entity/33618-fe-dependencies-stroomlijnen-valtimo-frontend-libraries
=> fix: upgrade moment

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/form-link/src/lib/components/form-link-process-diagram/form-link-process-diagram.component.ts, projects/valtimo/form-link/src/lib/components/process-link/process-link.component.ts, projects/valtimo/form-link/src/lib/models/form-link.model.ts, projects/valtimo/plugin/src/lib/plugins/open-zaak/components/open-zaak-configuration/open-zaak-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/smart-documents/components/smart-documents-configuration/smart-documents-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/smart-documents/smart-documents-plugin.specification.ts, projects/valtimo/user-interface/assets/design-tokens.css, projects/valtimo/user-interface/src/lib/components/button/button.component.html, projects/valtimo/user-interface/src/lib/components/button/button.component.scss, projects/valtimo/user-interface/src/lib/components/button/button.component.ts, projects/valtimo/user-interface/src/lib/components/input/input.component.html, projects/valtimo/user-interface/src/lib/components/input/input.component.scss, projects/valtimo/user-interface/src/lib/components/input/input.component.ts, projects/valtimo/user-interface/src/lib/components/input/input.module.ts, projects/valtimo/user-interface/src/lib/models/button.ts, projects/valtimo/user-interface/src/lib/models/input.ts
Addresses comments on https://ritense.tpondemand.com/entity/36255-fe-result-variable-of-smartdocuments-plugin and https://ritense.tpondemand.com/entity/36024-fe-opslaan-plugin-actie-configuratie-proceskoppelingen. Adjust texts to mention plugin actions instead of plugin functions. Changes inputs of secrets to password inputs on plugin configs
=> feat: address FE comments on saving plugin actions

projects/valtimo/plugin/src/lib/components/plugin-configuration-container/plugin-configuration-container.component.ts, projects/valtimo/plugin/src/lib/models/plugin.ts, projects/valtimo/plugin/src/lib/plugins/documenten-api/components/documenten-api-configuration/documenten-api-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/documenten-api/components/store-temp-document/store-temp-document-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/open-zaak/components/create-zaak-configuration/create-zaak-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/open-zaak/components/open-zaak-configuration/open-zaak-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/open-zaak/components/set-besluit-configuration/set-besluit-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/open-zaak/components/set-resultaat-configuration/set-resultaat-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/open-zaak/components/set-status-configuration/set-status-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/smart-documents/components/generate-document-configuration/generate-document-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/smart-documents/components/smart-documents-configuration/smart-documents-configuration.component.ts
Some properties from my solution design ended up not being used. Also, the configurationTitle property for a PluginConfigurationComponent is now required.
=> fix: improve fe plugin interfaces

projects/valtimo/components/src/lib/components/topbar/topbar.component.html, projects/valtimo/components/src/lib/components/topbar/topbar.component.scss, projects/valtimo/components/src/lib/components/topbar/topbar.component.ts, projects/valtimo/components/src/lib/components/topbar/topbar.module.ts, projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/user-interface/assets/design-tokens.css, projects/valtimo/user-interface/src/lib/components/paragraph/paragraph.component.html, projects/valtimo/user-interface/src/lib/components/paragraph/paragraph.component.ts, projects/valtimo/user-interface/src/lib/components/paragraph/paragraph.module.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
With feature toggle. Closes https://ritense.tpondemand.com/entity/36297-fe-fullname-weergeven-naast-avatar-in
=> feat: show full name in header

package-lock.json, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/plugin-management/src/lib/components/plugin-configure/plugin-configure.component.html, projects/valtimo/plugin-management/src/lib/components/plugin-configure/plugin-configure.component.ts, projects/valtimo/plugin-management/src/lib/components/plugin-edit-modal/plugin-edit-modal.component.html, projects/valtimo/plugin-management/src/lib/components/plugin-edit-modal/plugin-edit-modal.component.scss, projects/valtimo/plugin-management/src/lib/components/plugin-edit-modal/plugin-edit-modal.component.ts, projects/valtimo/plugin-management/src/lib/components/plugin-edit/plugin-edit.component.html, projects/valtimo/plugin-management/src/lib/components/plugin-edit/plugin-edit.component.scss, projects/valtimo/plugin-management/src/lib/components/plugin-edit/plugin-edit.component.ts, projects/valtimo/plugin-management/src/lib/components/plugin-management/plugin-management.component.html, projects/valtimo/plugin-management/src/lib/components/plugin-management/plugin-management.component.ts, projects/valtimo/plugin-management/src/lib/plugin-management.module.ts, projects/valtimo/plugin-management/src/lib/services/plugin-management-state.service.ts, projects/valtimo/plugin-management/src/lib/services/plugin-management.service.ts, projects/valtimo/plugin-management/src/public-api.ts, projects/valtimo/plugin/src/lib/plugins/documenten-api/components/documenten-api-configuration/documenten-api-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/documenten-api/components/documenten-api-configuration/documenten-api-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/open-zaak/components/open-zaak-configuration/open-zaak-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/open-zaak/components/open-zaak-configuration/open-zaak-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/smart-documents/components/smart-documents-configuration/smart-documents-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/smart-documents/components/smart-documents-configuration/smart-documents-configuration.component.ts
Closes https://ritense.tpondemand.com/entity/35309-fe-wijzigen-bestaande-plugin-configuratie-plugin
=> feat: edit and delete plugin configs

package-lock.json, package.json, projects/valtimo/swagger/package.json
=> fix: lock swagger-ui 4.12.0

projects/valtimo/dossier/src/lib/dossier-supporting-process-start-modal/dossier-supporting-process-start-modal.component.html, projects/valtimo/dossier/src/lib/dossier-supporting-process-start-modal/dossier-supporting-process-start-modal.component.ts, projects/valtimo/task/src/lib/task-detail-modal/task-detail-modal.component.html, projects/valtimo/task/src/lib/task-detail-modal/task-detail-modal.component.ts
Solves no message being displayed:
(Some code automatically reformatted, please ignore)
=> fix no form definition found warning message

projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/dossier/src/lib/dossier.service.ts
* add default sort direction on the default column
US: https://ritense.tpondemand.com/entity/36161-fe-configurable-sorting-direction-case-list
=> feat: configurable sorting direction case list columns

projects/valtimo/dossier/src/lib/dossier.service.ts
add type coercion to direction variable
US: https://ritense.tpondemand.com/entity/36161-fe-configurable-sorting-direction-case-list
=> fix: add type coercion to direction variable

projects/valtimo/user-interface/src/lib/directives/index.ts, projects/valtimo/user-interface/src/lib/directives/v-tooltip/index.ts
=> fix: tooltip exports

projects/valtimo/plugin/src/lib/plugins/documenten-api/components/documenten-api-configuration/documenten-api-configuration.component.html, projects/valtimo/user-interface/src/lib/components/input/input.component.html, projects/valtimo/user-interface/src/lib/components/input/input.component.ts, projects/valtimo/user-interface/src/lib/models/input.ts
Closes comment on https://ritense.tpondemand.com/entity/36267-be-store-documenten-via-documenten-api
=> fix: allow 0 at start of rsin input

projects/valtimo/components/src/lib/components/searchable-dropdown/searchable-dropdown.component.html, projects/valtimo/components/src/lib/components/searchable-dropdown/searchable-dropdown.component.scss
Closes https://ritense.tpondemand.com/entity/36781-fe-searchable-dropdown-does-not-display
=> fix: local searchable dropdown

projects/valtimo/components/src/lib/components/left-sidebar/left-sidebar.component.ts, projects/valtimo/config/src/lib/models/config.ts, src/environments/environment.ts
* saving menu width at localstorage
* add custom left sidebar width
US: https://ritense.tpondemand.com/entity/36474-autofit-width-for-document-definition-name
=> feat: autofit width for document definition name

projects/valtimo/user-interface/assets/design-tokens.css, projects/valtimo/user-interface/src/lib/components/table/table.component.scss
* fix table border to keep it rounded
=> style: fix table border to keep it rounded

projects/valtimo/layout/assets/css/app.css, projects/valtimo/user-interface/assets/design-tokens.css, projects/valtimo/user-interface/src/lib/components/input/input.component.scss, projects/valtimo/user-interface/src/lib/components/select/select.component.scss
* add outline at ng-select dropdown
* change input border to outline
=> style: change select and input border to outline

package-lock.json, projects/valtimo/dossier/src/lib/dossier-detail/tab/documents/documents.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/documents/documents.component.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/openzaak-documents/openzaak-documents.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/openzaak-documents/openzaak-documents.component.scss, projects/valtimo/dossier/src/lib/dossier-detail/tab/openzaak-documents/openzaak-documents.component.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/s3-documents/s3-documents.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/s3-documents/s3-documents.component.scss, projects/valtimo/dossier/src/lib/dossier-detail/tab/s3-documents/s3-documents.component.ts, projects/valtimo/dossier/src/lib/dossier.module.ts, src/environments/environment.ts
Document tab component switches between new S3 or OpenZaak component based on upload provider config in environment. Closes https://ritense.tpondemand.com/entity/37198-fe-create-new-tab-component-for
=> feat: separate s3 and openzaak upload tabs

projects/valtimo/user-interface/src/lib/components/select/select.component.html
... then the select box itself
=> feature 36899 - Labels of v-select can now be longer

package-lock.json, projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/documents/documents.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/documents/documents.component.ts, projects/valtimo/resource/src/lib/services/upload-provider.service.ts, src/environments/environment.ts
Remove feature flag; add dedicated documenten api upload provider
=> feat: add documenten api upload provider

projects/valtimo/plugin/src/lib/plugins/documenten-api/components/store-uploaded-document/store-uploaded-document-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/documenten-api/components/store-uploaded-document/store-uploaded-document-configuration.component.scss, projects/valtimo/plugin/src/lib/plugins/documenten-api/components/store-uploaded-document/store-uploaded-document-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/documenten-api/documenten-api-plugin.module.ts, projects/valtimo/plugin/src/lib/plugins/documenten-api/documenten-api-plugin.specification.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/link-uploaded-document-to-zaak/link-uploaded-document-to-zaak-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/link-uploaded-document-to-zaak/link-uploaded-document-to-zaak-configuration.component.scss, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/link-uploaded-document-to-zaak/link-uploaded-document-to-zaak-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/zaken-api-plugin.module.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/zaken-api-plugin.specification.ts, projects/valtimo/plugin/src/public-api.ts
Closes https://ritense.tpondemand.com/entity/37428-fe-create-components-for-new-plugin
=> feat: add new action configuration components

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.ts, projects/valtimo/dossier/src/lib/dossier-process-start-modal/dossier-process-start-modal.component.ts, projects/valtimo/resource/src/lib/models/upload.model.ts, projects/valtimo/resource/src/lib/services/open-zaak-upload.service.ts, projects/valtimo/resource/src/lib/services/upload-provider.service.ts
US: https://ritense.tpondemand.com/entity/37206-fe-check-whether-upload-process-has
=> feat: get document types from catalogi api

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/document/src/lib/document.service.ts, projects/valtimo/document/src/lib/models/document.model.ts, projects/valtimo/dossier-management/src/lib/dossier-management-detail/dossier-management-detail.component.html, projects/valtimo/dossier-management/src/lib/dossier-management-link-process/dossier-management-link-process.component.html, projects/valtimo/dossier-management/src/lib/dossier-management-link-process/dossier-management-link-process.component.scss, projects/valtimo/dossier-management/src/lib/dossier-management-link-process/dossier-management-link-process.component.ts, projects/valtimo/dossier-management/src/lib/dossier-management.module.ts, projects/valtimo/user-interface/src/lib/components/select/select.component.ts
=> feat: configure upload process on case management page

projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.html, projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.ts
Closes https://ritense.tpondemand.com/entity/37073-fe-prefill-author-for-metadata-when
=> feat: prefill author documenten api metadata

projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.ts
=> fix: null error

projects/valtimo/components/src/lib/components/form-io/documenten-api-uploader/documenten-api-uploader.component.html, projects/valtimo/components/src/lib/components/form-io/documenten-api-uploader/documenten-api-uploader.component.ts, projects/valtimo/resource/src/lib/models/upload.model.ts, projects/valtimo/resource/src/lib/services/open-zaak-upload.service.ts, projects/valtimo/resource/src/lib/services/open-zaak.service.ts, projects/valtimo/resource/src/lib/services/upload-provider.service.ts
Dependent on BE branch feature/37224_Implement_new_endpoint_for_uploading_form_files_to_local_file_storage. Closes https://ritense.tpondemand.com/entity/37540-fe-implement-new-be-endpoints-for
=> feat: implement be endpoints temp documenten api file upload

projects/valtimo/task/src/lib/assign-user-to-task/assign-user-to-task.component.ts
The assign user subscription was never killed and would still being loading even if the task was already finished. With destroying the subscription it should no longer be loading after the task is already completed.
Story: https://ritense.tpondemand.com/RestUI/Board.aspx#page=board/5259761390329663757&appConfig=eyJhY2lkIjoiOTNEM0VBODczQkE2RUIzQUJDQTJGNUUxMUM0MDBFN0EifQ==&boardPopup=bug/37443/silent
=> Add and remove subscription when component is destroyed

projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.html, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts
- While loading the cases on the case list page, a loading icon is shown
US: https://ritense.tpondemand.com/entity/37037-fe-loading-icon-on-case-list
=> feat: add loading icon at list cases

projects/valtimo/resource/src/lib/services/open-zaak.service.ts
Closes https://ritense.tpondemand.com/entity/37567-fe-support-empty-values-for-storing
=> fix: remove null values when submitting documenten api files

projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.html, projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.scss, projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.ts, projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.module.ts, projects/valtimo/components/src/lib/models/documenten-api-metadata.model.ts, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json
Closes https://ritense.tpondemand.com/entity/37494-fe-business-logic-for-storing-document
=> feat: documenten api business logic

projects/valtimo/components/src/lib/components/documenten-api-metadata-modal/documenten-api-metadata-modal.component.ts
=> fix: clear additional date selection on close metadata modal

projects/valtimo/user-interface/package.json
=> fix: add flatpickr dep

projects/valtimo/document/src/lib/models/document.model.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts, src/environments/environment.ts
US: https://ritense.tpondemand.com/entity/37406-fe-show-case-assignee-in-case
=> fix: show case assignee

projects/valtimo/components/src/lib/components/form-io/form-io.component.html, projects/valtimo/components/src/lib/components/form-io/form-io.component.ts
Closes https://ritense.tpondemand.com/entity/37068-fe-flatpickr-component-fails-to-load
=> fix: locale issue formio date picker

package-lock.json, projects/valtimo/dossier/src/lib/dossier-detail/dossier-detail.component.html, projects/valtimo/dossier/src/lib/dossier-detail/dossier-detail.component.ts
Closes https://ritense.tpondemand.com/entity/37407-fe-show-case-assignee-on-case
=> feat: show assignee on case detail page

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json
DocumentAssigneeChangedEvent will show the name of the assignee that was set
=> feature 37421 - Added translations for new events

package-lock.json, package.json, projects/valtimo/components/src/lib/components/search-fields/search-fields.component.html, projects/valtimo/components/src/lib/components/search-fields/search-fields.component.scss, projects/valtimo/components/src/lib/components/search-fields/search-fields.component.ts, projects/valtimo/components/src/lib/components/search-fields/search-fields.module.ts, projects/valtimo/components/src/public_api.ts, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/config/src/lib/models/search.model.ts, projects/valtimo/document/src/lib/document.service.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.html, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts, projects/valtimo/dossier/src/lib/dossier.module.ts, projects/valtimo/dossier/src/lib/models/index.ts, projects/valtimo/dossier/src/lib/models/search.model.ts, projects/valtimo/user-interface/assets/design-tokens.css, projects/valtimo/user-interface/src/lib/components/date-picker/date-picker.component.html, projects/valtimo/user-interface/src/lib/components/date-picker/date-picker.component.ts, projects/valtimo/user-interface/src/lib/components/form/form.component.html, projects/valtimo/user-interface/src/lib/components/form/form.component.ts, projects/valtimo/user-interface/src/lib/components/input-label/input-label.component.html, projects/valtimo/user-interface/src/lib/components/input-label/input-label.component.scss, projects/valtimo/user-interface/src/lib/components/input-label/input-label.component.ts, projects/valtimo/user-interface/src/lib/components/input/input.component.html, projects/valtimo/user-interface/src/lib/components/input/input.component.ts, src/environments/environment.ts
Not completed; development code behind feature flag. Please approve for demo tomorrow. For: https://ritense.tpondemand.com/entity/37578-fe-show-case-search-fields
=> feat: add front-end case search fields

projects/valtimo/config/assets/core/nl.json
- Changed plug-in to plugin, to create 1 conform spelling of plugin.
- Removed the dash between 'plugin' and 'naam' in the pluginName of the pluginManagement
=> Changed plug-in in the nl.json file to plugin

package-lock.json, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/config/src/lib/models/search.model.ts, projects/valtimo/document/src/lib/document.service.ts, projects/valtimo/dossier-management/src/lib/dossier-management-detail/dossier-management-detail.component.html, projects/valtimo/dossier-management/src/lib/dossier-management-detail/dossier-management-detail.component.ts, projects/valtimo/dossier-management/src/lib/dossier-management-search-fields/dossier-management-search-fields.component.html, projects/valtimo/dossier-management/src/lib/dossier-management-search-fields/dossier-management-search-fields.component.scss, projects/valtimo/dossier-management/src/lib/dossier-management-search-fields/dossier-management-search-fields.component.ts, projects/valtimo/dossier-management/src/lib/dossier-management.module.ts
Now shown on dossier detail page until separate search fields tab is finished. Hidden behind feature flag `caseSearchFields` so won't affect regular users. Closes https://ritense.tpondemand.com/entity/37583-fe-component-for-list-of-configured
=> feat: component for showing configured case search fields

projects/valtimo/components/src/lib/components/search-fields/search-fields.component.html, projects/valtimo/components/src/lib/components/search-fields/search-fields.component.scss
closes US: https://ritense.tpondemand.com/entity/40195-fe-feedback-case-search-fields
=> style: change search fields layout

package-lock.json, projects/valtimo/auth0/src/lib/auth0-user.service.ts, projects/valtimo/authority/src/lib/authority.service.ts, projects/valtimo/choice-field/src/lib/choice-field.service.ts, projects/valtimo/choicefield/src/lib/choicefield.service.ts, projects/valtimo/components/src/lib/components/version/version.service.ts, projects/valtimo/config/src/lib/services/menu-include.service.ts, projects/valtimo/connector-management/src/lib/services/connector-management/connector-management.service.ts, projects/valtimo/connector-management/src/lib/services/object-api-sync/object-api-sync.service.ts, projects/valtimo/contact-moment/src/lib/contact-moment.service.ts, projects/valtimo/context/src/lib/context.service.ts, projects/valtimo/customer/src/lib/services/customer.service.ts, projects/valtimo/document/src/lib/document.service.ts, projects/valtimo/dossier/src/lib/services/zaakobjecten.service.ts, projects/valtimo/form-link/src/lib/services/form-flow.service.ts, projects/valtimo/form-link/src/lib/services/form-link.service.ts, projects/valtimo/form-link/src/lib/services/process-link.service.ts, projects/valtimo/form-management/src/lib/form-management.service.ts, projects/valtimo/form/src/lib/form.service.ts, projects/valtimo/milestone/src/lib/milestone.service.ts, projects/valtimo/plugin/src/lib/services/plugin-management.service.ts, projects/valtimo/process/src/lib/process.service.ts, projects/valtimo/resource/src/lib/services/open-zaak-upload.service.ts, projects/valtimo/resource/src/lib/services/open-zaak.service.ts, projects/valtimo/resource/src/lib/services/s3.service.ts, projects/valtimo/security/src/lib/user-provider.service.ts, projects/valtimo/task/src/lib/task.service.ts, projects/valtimo/user-management/src/lib/user-management.service.ts, projects/valtimo/view-configurator/src/lib/view-configurator.service.ts
Closes https://ritense.tpondemand.com/entity/30694-be-fe-api-versioning
=> feat: add api versioning

projects/valtimo/keycloak/src/lib/callback.component.ts, projects/valtimo/keycloak/src/lib/keycloak.init.ts
Closes https://ritense.tpondemand.com/entity/37549-fe-keep-query-parameters-after-redirect
=> feat: keep query params after keycloak redirect

package-lock.json, projects/valtimo/components/src/lib/components/search-fields/search-fields.component.html, projects/valtimo/components/src/lib/components/search-fields/search-fields.component.ts, projects/valtimo/components/src/lib/components/search-fields/search-fields.module.ts, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/config/src/lib/models/search.model.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts, projects/valtimo/task/src/lib/task-list/task-list.component.ts, projects/valtimo/user-interface/src/lib/components/date-picker/date-picker.component.ts
Closes US: https://ritense.tpondemand.com/entity/42453-fe-add-missing-search-fields-and
=> feat: add missing search fields

projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.html, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts, projects/valtimo/form-link/src/lib/services/process-link.service.ts, src/environments/environment.ts
Requested change tabs order
US: https://ritense.tpondemand.com/entity/37416-fe-filter-cases-on-assignee-mine
=> fix: changed tabs order

package-lock.json, projects/valtimo/components/src/lib/components/right-sidebar/right-sidebar.component.ts, projects/valtimo/decision/src/lib/decision.service.ts, projects/valtimo/process-management/src/lib/process-management.service.ts, projects/valtimo/process/src/lib/process.service.ts
Closes https://ritense.tpondemand.com/entity/37351-be-fe-override-existing-camunda-endpoint
=> feat: change camunda endpoints

projects/valtimo/components/src/lib/components/right-sidebar/right-sidebar.component.scss, projects/valtimo/components/src/lib/components/right-sidebar/right-sidebar.component.ts
=> fix: right sidebar empty settings and layout

projects/valtimo/security/src/lib/error/http-error.interceptor.ts
=> feat: improved error messages

package-lock.json, projects/valtimo/components/src/lib/components/menu/menu.service.ts, projects/valtimo/document/src/lib/models/document.model.ts, projects/valtimo/dossier/src/lib/dossier-detail/dossier-detail.component.html, projects/valtimo/dossier/src/lib/dossier-detail/dossier-detail.component.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.html, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts
=> feat: only show assignee functionality and open case count if relevant

package-lock.json, projects/valtimo/components/src/lib/components/view-content/type-converters/booleanTypeConverter.ts, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/document/src/lib/document.service.ts, projects/valtimo/document/src/lib/models/document.model.ts, projects/valtimo/dossier-management/src/lib/dossier-management-detail-container/dossier-management-detail-container.component.ts, projects/valtimo/dossier-management/src/lib/dossier-management-detail-container/tabs/dossier-management-list-columns/dossier-management-list-columns.component.html, projects/valtimo/dossier-management/src/lib/dossier-management-detail-container/tabs/dossier-management-list-columns/dossier-management-list-columns.component.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts, projects/valtimo/dossier/src/lib/dossier.service.ts, projects/valtimo/dossier/src/lib/services/dossier-column.service.ts, projects/valtimo/dossier/src/lib/services/index.ts, projects/valtimo/dossier/src/public_api.ts, src/environments/environment.ts
Closes https://ritense.tpondemand.com/entity/43548-fe-show-configured-columns-on-case and partially https://ritense.tpondemand.com/entity/43547-fe-component-for-list-of-configured
=> feat: view case list columns and show in case list if configured

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/form-link/src/lib/services/form-flow.service.ts, projects/valtimo/task/src/lib/task-detail-modal/task-detail-modal.component.ts, projects/valtimo/user-interface/src/lib/components/prompt/prompt.component.html, projects/valtimo/user-interface/src/lib/components/prompt/prompt.component.scss, projects/valtimo/user-interface/src/lib/components/prompt/prompt.component.ts, projects/valtimo/user-interface/src/lib/services/prompt.service.ts
=> #45858 Form flow - store submission data when moving to the previous step

projects/valtimo/components/src/lib/components/timeline/timeline.component.html, projects/valtimo/layout/assets/css/app.css
Made with Jeroen van der Geest and made with ❤️
The audit time is now displayed next to the date
=> moved audit time to date

projects/valtimo/components/src/lib/components/topbar/topbar.component.scss
=> feat: Increase size of logo

package-lock.json, projects/valtimo/components/src/lib/components/topbar/topbar.component.html, projects/valtimo/components/src/lib/components/topbar/topbar.component.scss, projects/valtimo/components/src/lib/components/topbar/topbar.component.ts, projects/valtimo/config/src/lib/models/config.ts, src/environments/environment.prod.ts, src/environments/environment.test.ts, src/environments/environment.ts
=> feat: add option for large logo margin

projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json
=> feat: add missing translations

projects/valtimo/layout/assets/css/app.css
See [story](https://ritense.tpondemand.com/restui/board.aspx?#page=userstory/45195). 
- All audit trail dots now have the same color as the vertical line
=> TP-45195 - Make all audit trail dots the same color as the vertical line

package-lock.json, projects/valtimo/config/src/lib/models/config.ts, projects/valtimo/document/src/lib/document.service.ts, projects/valtimo/document/src/lib/models/document.model.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts, projects/valtimo/dossier/src/lib/services/dossier-column.service.ts
Closes https://ritense.tpondemand.com/entity/43550-fe-only-retrieve-configured-columns-from
=> feat: implement new document endpoint

projects/valtimo/document/src/lib/models/document.model.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts
=> feat: fix feedback 43550

projects/valtimo/components/assets/css/carbon-beagle-compatibility.scss, projects/valtimo/components/src/lib/components/dropzone/dropzone.component.scss, projects/valtimo/components/src/lib/components/searchable-dropdown/searchable-dropdown.component.scss, projects/valtimo/dossier/src/lib/dossier-detail/tab/summary/summary.component.html
Closes https://ritense.tpondemand.com/entity/49889-fe-fix-font-and-spacing-layout
=> fix: font sizing and spacing carbon

projects/valtimo/components/src/lib/components/left-sidebar/left-sidebar.component.scss, projects/valtimo/components/src/lib/services/shell.service.ts
Comments on https://ritense.tpondemand.com/entity/49890-fe-valtimo-main-menu-should-be
=> feat: address sidenav resize feedback

projects/valtimo/components/src/lib/components/menu/menu.service.ts
=> fix: roles support in left sidenav

package-lock.json, projects/valtimo/document/src/lib/document.service.ts
Closes https://ritense.tpondemand.com/entity/43173-fe-frontend-breaks-if-backend-throws
=> fix: resume after document search error

projects/valtimo/user-interface/src/lib/components/form/form.component.html
=> fix: prevent refresh on add row multi input

package-lock.json, projects/valtimo/components/assets/css/carbon-beagle-compatibility.scss, projects/valtimo/components/src/lib/components/left-sidebar/left-sidebar.component.scss
Addresses feedback on https://ritense.tpondemand.com/entity/49889-fe-fix-font-and-spacing-layout and https://ritense.tpondemand.com/entity/49890-fe-valtimo-main-menu-should-be
=> feat: address front-end feedback

projects/valtimo/form-management/src/lib/form-management-duplicate/form-management-duplicate.component.html, projects/valtimo/form-management/src/lib/form-management.module.ts
fixed the duplicate modal having unstyled buttons
=> tp-35799 fixed button layout for modal

projects/valtimo/dossier/src/lib/services/dossier-parameter.service.ts
Fix feedback on https://ritense.tpondemand.com/entity/48954-fe-support-search-parameters-in-url
=> feat: fix search on redirect

package-lock.json, projects/valtimo/plugin/src/lib/plugins/portaaltaak/components/portaaltaak-configuration/portaaltaak-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/portaaltaak/models/object.ts, projects/valtimo/plugin/src/lib/plugins/portaaltaak/services/index.ts, projects/valtimo/plugin/src/lib/plugins/portaaltaak/services/object.service.ts
=> fix: fix fe libs build

projects/valtimo/task/src/lib/task-detail-modal/task-detail-modal.component.scss
=> fix: fix broken task modal scroll

package-lock.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/object-management/src/lib/components/object-management-detail-container/object-management-detail-container.component.html, projects/valtimo/object-management/src/lib/components/object-management-detail-container/tabs/object-management-detail/object-management-detail.component.html, projects/valtimo/object-management/src/lib/components/object-management-detail-container/tabs/object-management-detail/object-management-detail.component.ts, projects/valtimo/object-management/src/lib/components/object-management-detail-container/tabs/object-management-list-columns/object-management-list-columns.component.html, projects/valtimo/object-management/src/lib/components/object-management-detail-container/tabs/object-management-list-columns/object-management-list-columns.component.ts, projects/valtimo/object-management/src/lib/components/object-management-detail-container/tabs/object-management-list-search-fields/object-management-list-search-fields.component.html, projects/valtimo/object-management/src/lib/components/object-management-detail-container/tabs/object-management-list-search-fields/object-management-list-search-fields.component.ts, projects/valtimo/object-management/src/lib/object-management.module.ts, projects/valtimo/object-management/src/lib/services/object-management.service.ts, projects/valtimo/object-management/src/lib/services/tab.enum.ts, projects/valtimo/plugin/src/lib/plugins/portaaltaak/components/complete-portal-task/complete-portal-task.component.html, projects/valtimo/plugin/src/lib/plugins/portaaltaak/components/complete-portal-task/complete-portal-task.component.scss, projects/valtimo/plugin/src/lib/plugins/portaaltaak/components/complete-portal-task/complete-portal-task.component.ts, projects/valtimo/plugin/src/lib/plugins/portaaltaak/components/portaaltaak-configuration/portaaltaak-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/portaaltaak/components/portaaltaak-configuration/portaaltaak-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/portaaltaak/portaaltaak-plugin.module.ts, projects/valtimo/plugin/src/lib/plugins/portaaltaak/portaaltaak-plugin.specification.ts, projects/valtimo/plugin/src/public-api.ts, projects/valtimo/user-interface/src/lib/components/input/input.component.html
- Plugin action: Complete portal task
- Added Plugin action property: document upload process process
=> feat: 47740 Complete Portal task

package-lock.json, projects/valtimo/plugin/src/lib/plugins/portaaltaak/components/create-portal-task/create-portal-task.component.html, projects/valtimo/plugin/src/lib/plugins/portaaltaak/components/create-portal-task/create-portal-task.component.ts, projects/valtimo/plugin/src/lib/plugins/portaaltaak/portaaltaak-plugin.specification.ts, projects/valtimo/user-interface/src/lib/components/multi-input/multi-input.component.ts
See last comment on https://ritense.tpondemand.com/entity/47092-fe-task-plugin-plugin-action-to
=> feat: address feedback create portal task plugin action

projects/valtimo/components/assets/css/carbon.scss, projects/valtimo/components/src/lib/components/menu/menu.service.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts, projects/valtimo/dossier/src/lib/services/dossier-parameter.service.ts
Also addresses some router issues caused by dossier list query parameters. Dossier list query parameters are now only shown in url on dossier list page. Also, the activated route is now correctly highlighted in the left sidenav on first opening a page from a url.
=> feat: ibm blue to ritense blue

projects/valtimo/document/src/lib/document.service.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.ts
Closes https://ritense.tpondemand.com/entity/53755-fe-use-new-endpoint-to-retrieve
=> feat: implement new zaken api related files endpoint

projects/valtimo/document/src/lib/models/document.model.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.ts
Closes https://ritense.tpondemand.com/entity/55522-fe-hide-time-from-documents-date
=> feat: hide times documenten api list

projects/valtimo/components/src/lib/components/left-sidebar/left-sidebar.component.html, src/environments/environment.ts
Story: https://ritense.tpondemand.com/entity/55245-fe-feature-toggle-for-menuitem-objecten
=> Enabled includeFunction on child level

projects/valtimo/document/src/lib/models/document.model.ts, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.ts
Closes https://ritense.tpondemand.com/entity/53758-fe-use-new-endpoint-to-opendownload
=> feat: download files using documenten api plugin

projects/valtimo/plugin/src/lib/plugins/objecten-api/components/delete-object/delete-object.component.html, projects/valtimo/plugin/src/lib/plugins/objecten-api/components/delete-object/delete-object.component.scss, projects/valtimo/plugin/src/lib/plugins/objecten-api/components/delete-object/delete-object.component.ts, projects/valtimo/plugin/src/lib/plugins/objecten-api/objecten-api-plugin-module.ts, projects/valtimo/plugin/src/lib/plugins/objecten-api/objecten-api-plugin.specification.ts, projects/valtimo/plugin/src/public-api.ts
Closes https://ritense.tpondemand.com/entity/48697-fe-objecten-api-plugin-new-plugin
=> feat: config component for delete object plugin action

projects/valtimo/user-interface/src/lib/components/input/input.component.html, projects/valtimo/user-interface/src/lib/components/input/input.component.ts, projects/valtimo/user-interface/src/lib/components/input/input.module.ts, projects/valtimo/user-interface/src/lib/components/modal/modal.component.html, projects/valtimo/user-interface/src/lib/components/modal/modal.component.ts
Closes https://ritense.tpondemand.com/entity/56479-fe-fields-and-buttons-productaanvraag-connector
=> fix: dropdown in productaanvragen connector

package-lock.json, projects/valtimo/components/src/lib/components/multi-input/carbon-multi-input.component.html, projects/valtimo/components/src/lib/components/multi-input/carbon-multi-input.component.scss, projects/valtimo/components/src/lib/components/multi-input/carbon-multi-input.component.ts, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.ts, projects/valtimo/dossier/src/lib/dossier.module.ts, projects/valtimo/object/src/lib/components/object-list/object-list.component.ts, projects/valtimo/plugin/src/lib/plugins/verzoek/components/verzoek-configuration/verzoek-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/verzoek/components/verzoek-configuration/verzoek-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/verzoek/verzoek-plugin.specification.ts, projects/valtimo/user-interface/src/lib/components/radio/radio.component.html, projects/valtimo/user-interface/src/lib/components/radio/radio.component.ts
Verzoek mapping better tooltip, column titles, and not {key;value} but {source;target}. Added warning on Documents API API documents tab when there is no zaak link. Fixed radio button not working anymore after reverting Kevin's. fix last week. Closed https://ritense.tpondemand.com/entity/47744-fe-verzoek-plugin-mapping-verzoek-object
=> feat: verzoek mapping feedback

projects/valtimo/plugin/src/lib/plugins/verzoek/components/verzoek-configuration/verzoek-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/verzoek/components/verzoek-configuration/verzoek-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/verzoek/models/config.ts
=> feat: fix verzoek mapping prefill

projects/valtimo/plugin/src/lib/plugins/verzoek/components/verzoek-configuration/verzoek-configuration.component.ts
=> fix: null check verzoektype mapping

projects/valtimo/components/src/lib/components/right-sidebar/right-sidebar.component.html, projects/valtimo/components/src/lib/components/right-sidebar/right-sidebar.component.ts
=> feat: add frontend version

package.json, projects/valtimo/components/src/lib/components/right-sidebar/right-sidebar.component.html, projects/valtimo/components/src/lib/components/right-sidebar/right-sidebar.component.scss, projects/valtimo/components/src/lib/components/right-sidebar/right-sidebar.component.ts, projects/valtimo/config/src/lib/constants/index.ts, projects/valtimo/config/src/lib/constants/versions.ts, projects/valtimo/config/src/lib/models/versions.model.ts, projects/valtimo/config/src/public-api.ts, scripts/copy-frontend-version.js
Closes https://ritense.tpondemand.com/entity/51229-febe-show-fe-libraries-version-git
=> feat: frontend version in sidebar with script

package.json, scripts/copy-frontend-version.js
=> feat: adjust copy version script

projects/valtimo/components/src/lib/components/list/list.component.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts
- When a custom date format is defined this is now passed through.
- Added support for dots in definition key
=> Bugfixes dossier list custom columns

projects/valtimo/components/src/lib/components/menu/menu.service.ts
Remove `@valtimo/sse` dependency so that from menu-component.
=> #58370 Remove server send events from menu

package-lock.json, projects/valtimo/components/src/lib/components/form-io/services/form-io-state.service.ts, projects/valtimo/components/src/lib/components/list/list.component.ts, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/create-niet-natuurlijk-persoon-zaak-rol/create-niet-natuurlijk-persoon-zaak-rol.component.html, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/create-niet-natuurlijk-persoon-zaak-rol/create-niet-natuurlijk-persoon-zaak-rol.component.scss, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/create-niet-natuurlijk-persoon-zaak-rol/create-niet-natuurlijk-persoon-zaak-rol.component.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/models/config.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/zaken-api-plugin.module.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/zaken-api-plugin.specification.ts, projects/valtimo/plugin/src/public-api.ts
=> #52875 plugin action 'Create Niet-natuurlijk Persoon Zaakrol'

projects/valtimo/plugin/src/lib/plugins/zaken-api/components/create-zaak-resultaat/create-zaak-resultaat-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/create-zaak-resultaat/create-zaak-resultaat-configuration.component.scss, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/create-zaak-resultaat/create-zaak-resultaat-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/set-zaak-status/set-zaak-status-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/set-zaak-status/set-zaak-status-configuration.component.scss, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/set-zaak-status/set-zaak-status-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/models/config.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/zaken-api-plugin.module.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/zaken-api-plugin.specification.ts, projects/valtimo/plugin/src/public-api.ts
I've skipped some acceptance criteria due to lack of FE knowledge.
=> #50041 Zaken Api plugin - new plugin action 'Set Zaakstatus'

projects/valtimo/components/src/lib/components/list/list.component.html, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.html, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.scss, projects/valtimo/dossier/src/lib/dossier-detail/tab/documenten-api-documents/documenten-api-documents.component.ts, projects/valtimo/dossier/src/lib/dossier.module.ts, projects/valtimo/plugin/src/lib/plugins/besluiten-api/besluiten-api-plugin.specification.ts, projects/valtimo/plugin/src/lib/plugins/catalogi-api/catalogi-api-plugin.specification.ts, projects/valtimo/resource/src/lib/services/download.service.ts
Closes https://ritense.tpondemand.com/entity/56813-fe-loading-icon-on-documents-tab
=> feat: loading icons on documenten api documents tab

projects/valtimo/dossier/src/lib/dossier-detail/tab/summary/summary.component.ts
For https://ritense.tpondemand.com/entity/51517-befe-quotes-in-case-fields-show
=> feat: sanitize html

package-lock.json, package.json, projects/valtimo/dossier/ng-package.json, projects/valtimo/dossier/package.json, projects/valtimo/dossier/src/lib/dossier-detail/tab/summary/summary.component.ts
=> feat: revert un-escpaing html

projects/valtimo/document/src/lib/document.service.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/create-zaak/create-zaak-configuration.component.html, projects/valtimo/plugin/src/lib/plugins/zaken-api/components/create-zaak/create-zaak-configuration.component.ts, projects/valtimo/plugin/src/lib/plugins/zaken-api/zaken-api-plugin.specification.ts
Closes https://ritense.tpondemand.com/entity/55025-fe-be-create-zaak-plugin-action
=> feat: only select linked zaak types

projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts
The solution for https://ritense.tpondemand.com/restui/board.aspx?#page=userstory/57090 to make sure that a user can search again with the same search query. This is needed for async data that could change in the backend.
=> Add search switch to make sure the search can always be trigger without having to change the search fields

projects/valtimo/components/src/lib/components/form-io/form-io-uploader/form-io-uploader.component.ts, projects/valtimo/components/src/lib/components/form-io/form-io-uploader/form-io-uploader.formio.ts, projects/valtimo/components/src/lib/components/form-io/form-io.component.ts
Closes https://ritense.tpondemand.com/entity/61113-fe-upload-field-doesnt-work-on
=> fix: upload field not appearing

projects/valtimo/components/src/lib/components/multi-input/carbon-multi-input.component.ts, projects/valtimo/components/src/lib/components/page-title/page-title.component.ts, projects/valtimo/dossier/src/lib/dossier-list/dossier-list.component.ts, projects/valtimo/object-management/src/lib/components/object-management-detail-container/tabs/object-management-list-columns/object-management-list-columns.component.ts, projects/valtimo/object-management/src/lib/components/object-management-detail-container/tabs/object-management-list-search-fields/object-management-list-search-fields.component.ts, projects/valtimo/object-management/src/lib/services/object-management.service.ts, projects/valtimo/object/src/lib/components/object-detail-container/tabs/object-detail/object-detail.component.html, projects/valtimo/object/src/lib/components/object-detail-container/tabs/object-detail/object-detail.component.ts, projects/valtimo/object/src/lib/components/object-list/object-list.component.ts, projects/valtimo/task/src/lib/task-detail-modal/task-detail-modal.component.ts, projects/valtimo/user-interface/src/lib/components/multi-input-form/multi-input-form.component.ts, projects/valtimo/user-interface/src/lib/components/multi-input/multi-input.component.ts
Fixes:
- More than 20 entries Template-data can't be set in SmartDocuments-Document genereren plugin action
- Run prettier
- formFlowInstanceId can be null (see image)
=> #61803 More than 20 entries

package-lock.json, projects/valtimo/config/assets/core/de.json, projects/valtimo/config/assets/core/en.json, projects/valtimo/config/assets/core/nl.json, projects/valtimo/form-link/src/lib/components/process-link-modal/process-link-modal.component.html, projects/valtimo/form-link/src/lib/components/select-form-flow/index.ts, projects/valtimo/form-link/src/lib/components/select-form-flow/select-form-flow.component.html, projects/valtimo/form-link/src/lib/components/select-form-flow/select-form-flow.component.scss, projects/valtimo/form-link/src/lib/components/select-form-flow/select-form-flow.component.ts, projects/valtimo/form-link/src/lib/form-link.module.ts, projects/valtimo/form-link/src/lib/models/process-link.model.ts, projects/valtimo/form-link/src/lib/services/process-link-state-2.service.ts, projects/valtimo/form-link/src/lib/services/process-link-step.service.ts, projects/valtimo/form-link/src/lib/services/process-link.service.ts
Closes https://ritense.tpondemand.com/entity/50048-fe-support-formflowprocesslinks
=> feat: support form flow process links

projects/valtimo/task/src/lib/task.service.ts
For: https://ritense.tpondemand.com/entity/61006-be-support-prefilled-forms-when-using
=> fix: circumvent process link 404 error
